# : Manager [[[

[manager]
cwd = { fg = "#ffffff" }

# Tab
tab_active = { fg = "#000000", bg = "#edefff", bold = true }
tab_inactive = { fg = "#dbe1ff", bg = "#000000" }
tab_width = 1

# Find
find_keyword = { fg = "#ffece9", bold = true, italic = true, underline = true }
find_position = { fg = "#ffece9", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff70e7", bg = "#ff70e7" }
marker_cut = { fg = "#ffd6f8", bg = "#ffd6f8" }
marker_marked = { fg = "#ffece9", bg = "#ffece9" }
marker_selected = { fg = "#ffeaf9", bg = "#ffeaf9" }

# Count
count_copied = { fg = "#000000", bg = "#ffd6f8" }
count_cut = { fg = "#000000", bg = "#ffd6f8" }
count_selected = { fg = "#000000", bg = "#ffeaf9" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#b4c5ff" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#000000", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#edefff", fg = "#000000", bold = true }
normal_alt  = { bg = "#474747", fg = "#ffffff" }

# Select mode
select_main = { bg = "#edefff", fg = "#000000", bold = true }
select_alt  = { bg = "#474747", fg = "#ffffff" }

# Unset mode
unset_main = { bg = "#ffeaf9", fg = "#000000", bold = true }
unset_alt  = { bg = "#474747", fg = "#ffffff" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#edefff", bg = "#505050" }
progress_error = { fg = "#ffece9", bg = "#505050" }

# Permissions
permissions_t = { fg = "#5467ff" }
permissions_w = { fg = "#ff51cd" }
permissions_x = { fg = "#ff6850" }
permissions_r = { fg = "#ff3dde" }
permissions_s = { fg = "#4262ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#edefff" }
active = { fg = "#ffeaf9", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#edefff" }
value = { fg = "#ffffff" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#edefff", bg = "#000000" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#edefff" }
title = {}
hovered = { fg = "#ffd6f8", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#505050" }
cand = { fg = "#edefff" }
rest = { fg = "#000000" }
desc = { fg = "#ffffff" }
separator = " ‚ñ∂ "
separator_style = { fg = "#ffffff" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ffffff" }
run = { fg = "#ffffff" }
footer = { fg = "#000000", bg = "#edefff" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#ffeaf9" }
title_warn = { fg = "#edefff" }
title_error = { fg = "#ffece9" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#ffaea4" },
    { name = "*", is = "exec", fg = "#000000" },

    # Fallback
    { name = "*", fg = "#ffffff" },
    { name = "*/", fg = "#b4c5ff" },
]

# : ]]]
